server:
  port: 2001
spring:
  application:
    name: seata2001
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: default

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.136.104.77:3306/seata
    username: root
    password:
